### ISSUE TITLE
UI: Store the calculator input values in state

### ISSUE THREAD

**Issue by hbeckeri** [pool-miner/risk-manager#4]

**Comment by scottjstewart** [comment]
what

**Comment by scottjstewart** [comment]
Do you want them visible or just have the information stored?

**Comment by hbeckeri** [comment]
I want the data stored in state to be visible in each respective textfield. Can you default them all to `0` except for risk amount, which should be `2`?

**Comment by scottjstewart** [comment]
hmm im not quite understanding what you mean? should it remove previous data when people make a new entry or do you want a permanent history for each user?

**Comment by scottjstewart** [comment]
lecture is done for today so ill be home after lunch 
 
you can just show me then.

**Comment by scottjstewart** [comment]
use on change got it

**Comment by hbeckeri** [comment]
Essentially something like
```
<Textfield onChange={this.onChangeTextField.bind(this)}/>
.
.
.
onChange(evt) {
    evt.preventDefault();

    let value = evt.target.value; // Value in the textfield

   this.setState({ key: value });
}
```
